### PR TITLE
Making GDAL optional

### PR DESCRIPTION
**Pull request by Kelvinrr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Kelvinrr** [comment]
@conda-forge-admin, please rerender

**Comment by Kelvinrr** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
oh, and there's `scripts`... those would ideally be turned into `entry_points: console_scripts` so conda-build can make nice wrappers for them.

**Comment by bollwyvl** [comment]
I'll very likely wander off for the day, but feel free to plunder anything you like about #26 :pirate_flag:

**Comment by bollwyvl** [comment]
(of note, once the [build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=626023&view=logs&j=82c052c7-1553-5526-de9e-b02ac4ff0cc4&t=4ec9964f-699a-526c-51e8-c9bb37a5d3b4) finishes, you might be able to download, look at, and maybe locally test the packages it builds)

**Comment by Kelvinrr** [comment]
@conda-forge-admin, please update circle

**Comment by Kelvinrr** [comment]
Poached changes from #26 

Testing the artifact locally works fine, thanks @bollwyvl for the assistance.

**Comment by Kelvinrr** [comment]
idk what's with the circle-CI issues but I am choosing to ignore them for now.

**Pull request merged**
